name: polyapp_example
description: Demonstrates how to use the polyapp plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  polyapp:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter